#!/usr/bin/env python3
"""Build step: encrypt passwords from secrets.h into cipher.h for the ESP32.

Usage: gen_cipher.py <secrets.h> <public_key.pem> <cipher.h>
"""
import re
import sys

from cryptography.hazmat.primitives import hashes, serialization
from cryptography.hazmat.primitives.asymmetric import padding

OAEP = padding.OAEP(mgf=padding.MGF1(hashes.SHA256()),
                    algorithm=hashes.SHA256(), label=None)


def main(secrets_path, pubkey_path, out_path):
    src = open(secrets_path).read()
    token = re.search(r'#define\s+AUTH_TOKEN\s+"([^"]*)"', src).group(1)
    pub = serialization.load_pem_public_key(open(pubkey_path, "rb").read())
    size = pub.key_size // 8

    lines = ["// generated by typer/gen_cipher.py - do not edit",
             "#define CIPHER_LEN %d" % size]
    for i in (1, 2):
        m = re.search(r'PASSWORD_%d\[\]\s*=\s*"([^"]*)"' % i, src)
        pwd = m.group(1) if m else ""
        if not pwd:
            lines.append("#define CIPHER_%d NULL" % i)
            continue
        enc = pub.encrypt(("%s %s\n" % (token, pwd)).encode(), OAEP)
        body = ", ".join("0x%02x" % b for b in enc)
        lines.append("const uint8_t CIPHER_%d[CIPHER_LEN] = { %s };" % (i, body))

    with open(out_path, "w") as f:
        f.write("\n".join(lines) + "\n")
    print("wrote %s" % out_path)


if __name__ == "__main__":
    main(*sys.argv[1:4])
